Resolve testcontainers issue
Resolve
```
Error:  com.redhat.idaas.dream.demo.UsingKafkaIT  Time elapsed: 1.451 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=confluentinc/cp-kafka:5.4.3, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException:
Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
```

as in
https://github.com/RedHat-Healthcare/iDaaS-Demos/runs/2191620164#step:4:2596